# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    view:
        # We ask FOSRestBundle to  intercep the object and serailize it for us
        view_response_listener:  true
        # Only these formats are accepted for the serialization
        formats: { json: true, xml: false, rss: false }
    # The conversion from JSON to PHP object in now automatic
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: violations
    # We as FOSRestBundle to allow empty object's field in the serialized object
    # If false, the field will not be displayed
    serializer:
        serialize_null: true
    format_listener:
        rules:
            # For all routes starting with /api, objects returned by actions must be JSON serialized
            # in priority
            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json ] }
            - { path: '^/', priorities: [ 'html', '*/*'], fallback_format: html, prefer_extension: true }
    # use this to validate POST and GET parameters sent by user
    param_fetcher_listener: force
    exception:
        enabled: true
        codes:
            { App\Exception\ResourceValidationException: 400, \Exception: 500 }
        messages:
           { App\Exception\ResourceValidationException: true }

knp_paginator:
    page_range: 5                       # number of links showed in the pagination menu (e.g: you have 10 pages, a page_range of 3, on the 5th page you'll see links to page 4, 5, 6)
    default_options:
        page_name: page                 # page query parameter name
        sort_field_name: sort           # sort field query parameter name
        sort_direction_name: direction  # sort direction query parameter name
        distinct: true                  # ensure distinct results, useful when ORM queries are using GROUP BY statemen